name: iso_build
on:
  workflow_dispatch:
  schedule:
    - cron:  '30 2 * * 1'
permissions:
  contents: write  # Ez ad jogot a release-ek kezeléséhez
  actions: read
jobs:
  prepare-release:
    runs-on: ubuntu-24.04
    steps:
      - 
        #uses: styfle/cancel-workflow-action@0.9.0 
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}
      - 
        id: time
        uses: nanzm/get-time-action@v1.1
        with:
          format: 'YYYYMMDDHHmm'
    outputs:
      release_tag: ${{ steps.time.outputs.time }}
  build-release:
    runs-on: ubuntu-24.04
    needs: [prepare-release]
    strategy:
      matrix:
        EDITION: [xfce]
        BRANCH: [stable]
        SCOPE: [full]
    steps:
      - 
        #uses: styfle/cancel-workflow-action@0.9.0 
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}
      - 
        id: time
        uses: nanzm/get-time-action@v1.1
        with:
          format: 'YY.MM'   
      -
        name: image-build-upload
        uses: manjaro/manjaro-iso-action@main
        with:
          iso-profiles-repo: 'https://github.com/megvadulthangya/iso-profiles'
          edition: ${{ matrix.edition }}
          branch: ${{ matrix.branch }}
          scope: ${{ matrix.scope }}
          version: ${{ steps.time.outputs.time }}-Nordic-awesome
          kernel: linux612
          code-name: "nordic-awesome-Build"
          release-tag: ${{ needs.prepare-release.outputs.release_tag }}
      -
        name: rollback
        if: ${{ failure() || cancelled() }}
        run: |
          echo ${{ github.token }} | gh auth login --with-token
          gh release delete ${{ needs.prepare-release.outputs.release_tag }} -y --repo ${{ github.repository }}
